---
- name: "package install misc"
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
    - "aptitude"
- name: "install docker-cc"
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
     - docker-ce

